param(
    [string]$ProjectRoot = (Split-Path -Parent $PSScriptRoot)
)

$factoryPath = Join-Path $ProjectRoot "src/ServerScriptService/MobModelFactory.lua"
$visualsPath = Join-Path $ProjectRoot "src/ServerScriptService/EnemyVisuals.server.lua"
$outputPath = Join-Path $ProjectRoot "enemy-model-installer.lua"

$factory = Get-Content -LiteralPath $factoryPath -Raw -Encoding utf8
$visuals = Get-Content -LiteralPath $visualsPath -Raw -Encoding utf8

$template = @'
-- ASHEN VIGIL: ENEMY MODEL INSTALLER
-- GENERATED by tools/build-enemy-model-installer.ps1. Do not hand-edit.
-- Paste this entire file into View > Command Bar, then press Enter once.

local ServerScriptService = game:GetService("ServerScriptService")
local ServerStorage = game:GetService("ServerStorage")

local function replace(className, name, parent, source)
	local old = parent:FindFirstChild(name)
	if old then
		old:Destroy()
	end
	local object = Instance.new(className)
	object.Name = name
	object.Source = source
	object.Parent = parent
	return object
end

local factoryModule = replace("ModuleScript", "MobModelFactory", ServerScriptService, [====[
__FACTORY__
]====])

replace("Script", "EnemyVisuals", ServerScriptService, [====[
__VISUALS__
]====])

local oldTemplates = ServerStorage:FindFirstChild("AshenVigilEnemyModels")
if oldTemplates then
	oldTemplates:Destroy()
end
local templates = Instance.new("Folder")
templates.Name = "AshenVigilEnemyModels"
templates.Parent = ServerStorage

local factory = require(factoryModule)
for _, enemyId in ipairs({ "Bat", "Ghoul", "Brute", "Warden" }) do
	factory.CreatePreview(enemyId, templates, CFrame.new())
end

print("Ashen Vigil enemy models installed! Four templates are in ServerStorage; press Play to see them in combat.")
'@

$template = $template.Replace("__FACTORY__", $factory.TrimEnd())
$template = $template.Replace("__VISUALS__", $visuals.TrimEnd())
Set-Content -LiteralPath $outputPath -Value $template -Encoding utf8
Write-Output "Built $outputPath"
